### ISSUE TITLE
Stops working under ExtJS 4.1.1

### ISSUE THREAD

**Issue by brian428** [matsbryntse/ExtJS4-Lockable-Tree#2]
Thank's a lot for this work, it really helped me implement a similar feature in my current project.

However, just FYI, the component stops working with ExtJS 4.1.1. Error in LockableBufferedTree.js, line 261. Basically the DOM element for the "normal grid" is no longer ready at the point updateSpacer() is firing. (Cannot read property 'dom' of undefined.)

I tried adding another condition to the if block for "&& this.normalGrid.getView().rendered". That skips this error but leads to more further down in the guts of ext-all-debug. Framework tries to call setHeight() on the DOM element of a CompositeElement (which I believe is the verticalScroller.stretcher). I tried to keep digging, but unfortunately I didn't get any further. At that point it's so deep into the layout or rendering cycle that I'm over my head and really not sure what to try and look for.

I have SVN access so I tried to compare tags for 4.1.0 and 4.1.1 to see if I could narrow down the change that is causing this, but it looks like the tags aren't publicly accessible. :-/  

Regards,

Brian

**Comment by matsbryntse** [comment]
Right, we've noticed this as well. Right now it seems the TreePanel + buffering mechanisms are in too much flux to motivate a fix right now. I'll probably take another look at this in 4.1.2. Feel free to ping me if you haven't seen this updated after 4.1.2 is out :)

**Comment by matsbryntse** [comment]
Did you try it using 4.1.2? Haven't had time to check your PRs yet, do they also work well with 4.1.2?

**Comment by brian428** [comment]
Just tested with 4.1.2 and it appears to work correctly (with the changes in my pull requests). I'll try to test it with the original code as well, but this is encouraging (that it seems to fix the dom undefined error).

**Comment by brian428** [comment]
Just a note that you may want to update the readme to mention that support for locking and buffered trees was added in 4.2. I'll go ahead and close this. Thanks.
